project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bids do
  	member do
  		post :approve
  	end
  end
  resources :stuffs do
  	member do
  		post :bid, to: 'stuffs#bid_stuff'
  	end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stuffs#index'

  resources :reports, only: [] do
    collection do
      get 'popular_pickup'
      get 'popular_return'
    end
  end
end

project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CS2102 stuff sharing</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/journal/bootstrap.min.css" rel="stylesheet" integrity="sha256-bPSyJP9+ovy9/YbIwvZyX6r2M4PkiF01vt0zuDLUEzs= sha512-F4ep7hh9V7i7UvRF56Vq8VgjFIFGRVaE2y5UZ2FtIcMWoLFiDxTmHgnDm1XDZGcc6Vtp+kwtL0Kd3VA8uBMK9g==" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js" %></script>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container main-container">
    <nav class="panel navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Stuff sharing</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to 'Users', users_path %>
              </li>
              <li>
                <%= link_to 'Stuffs', stuffs_path %>
              </li>
              <li>
                <%= link_to 'Bids', bids_path %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Popular Pickup Points', popular_pickup_reports_path %></li>
                  <li><%= link_to 'Popular Dropoff Points', popular_return_reports_path %></li>
                </ul>
              </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

    <div class="panel main-panel">
      <div class="panel-body">
        <%= yield %>
      </div>
    </div>
</div>
</body>
</html>