project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bids do
  	member do
  		post :approve
  	end
  end
  resources :stuffs do
  	member do
  		post :bid, to: 'stuffs#bid_stuff'
  	end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stuffs#index'

  resources :reports, only: [] do
    collection do
      get 'popular_pickup'
      get 'popular_return'
    end
  end
end

project/app/models/bid.rb
class Bid < ApplicationRecord
	self.primary_keys = :stuff_create_time, :owner_username, :bidder_username
  belongs_to :stuff
  belongs_to :user

  def self.get_bid(stuff_create_time, owner_username, bidder_username)
  	sql = "SELECT * FROM bids WHERE stuff_create_time='#{stuff_create_time}' AND "\
      "owner_username='#{owner_username}' AND "\
      "bidder_username='#{bidder_username}';"
    Bid.find_by_sql(sql).first
  end

  def self.new_bid(params)
    stuff_create_time = params[:stuff_create_time]
    owner_username = params[:owner_username]
    bidder_username = params[:bidder_username]
    bidding_points = params[:bidding_points]
    create_time = params[:create_time]

    stuff = Stuff.get_stuff(stuff_create_time, owner_username)
  	return false unless stuff.present?
  	bidder_username = User.get_user(bidder_username)
  	return false unless bidder_username.present?

    sql = "INSERT INTO bids "\
      "(stuff_create_time, owner_username, bidder_username, bidding_points, create_time) "\
      "VALUES ('#{stuff_create_time}', '#{owner_username}', '#{bidder_username}', '#{bidding_points}', '#{create_time}');"
    ActiveRecord::Base.connection.execute sql

    [stuff_create_time, owner_username, bidder_username, bidding_points, create_time]
  end

  def self.update_bid(stuff_create_time, owner_username, bidder_username, new_biding_points)
  	sql = "UPDATE bids "\
      "SET bidding_points = #{new_biding_points.to_i} "\
      "WHERE bids.stuff_create_time='#{stuff_create_time}' AND "\
      "bids.owner_username = '#{owner_username}' AND "\
      "bids.bidder_username = '#{bidder_username}';"
    ActiveRecord::Base.connection.execute sql
  end

  def self.delete_bid(stuff_create_time, owner_username, bidder_username)
    sql = "DELETE FROM bids "\
      "WHERE bids.stuff_create_time='#{stuff_create_time}' AND "\
      "bids.owner_username = '#{owner_username}' AND "\
      "bids.bidder_username = '#{bidder_username}';"
    ActiveRecord::Base.connection.execute sql
  end

  def self.pickup_bid(stuff_create_time, owner_username, bidder_username)
  	stuff = Stuff.get_stuff(stuff_create_time, owner_username)
  	#return false unless stuff.present?
  	bidder = User.get_user(bidder_username)
  	#return false unless bidder.present?
  	bid = Bid.get_bid(stuff_create_time, owner_username, bidder_username)
    stuff_create_time = stuff_create_time.to_datetime.strftime("%Y-%m-%d %H:%M:%S")
  	
  	sql1 = "UPDATE bids "\
      "SET status=1 "\
      "WHERE stuff_create_time='#{stuff_create_time}' AND "\
      "owner_username='#{owner_username}' AND "\
      "bidder_username='#{bidder_username}';"
    ActiveRecord::Base.connection.execute sql1

    sql2 = "UPDATE stuffs "\
      "SET availability=1 "\
      "WHERE create_time='#{stuff_create_time}' AND "\
      "owner_username='#{owner_username}';"
    ActiveRecord::Base.connection.execute sql2

    sql3 = "UPDATE users "\
      "SET points = points - #{bid.bidding_points.to_i} "\
      "WHERE users.username='#{bidder_username}';"
    ActiveRecord::Base.connection.execute sql3

    sql4 = "UPDATE users "\
      "SET points = points + #{bid.bidding_points.to_i} "\
      "WHERE users.username='#{owner_username}';"
    ActiveRecord::Base.connection.execute sql4
  end

  def self.get_stuff_bids(stuff_create_time, owner_username)
  	sql = "SELECT * FROM bids WHERE stuff_create_time='#{stuff_create_time} '"\
      "AND owner_username='#{owner_username}'"
    Bid.find_by_sql(sql)
  end

  def self.get_taken_stuff_bid(stuff_create_time, owner_username)
  	sql = "SELECT * FROM bids WHERE stuff_create_time='#{stuff_create_time}' AND "\
      "owner_username='#{owner_username}' AND status = 1;"
      Bid.find_by_sql(sql).first
  end
end

project/app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy, :approve]

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.delete
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    Bid.pickup_bid(@paramss[0], @paramss[1], @paramss[2])
    redirect_to stuffs_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @paramss = params[:id].split(',')
      @bid = Bid.get_bid(@paramss[0], @paramss[1], @paramss[2])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params[:bid][:bidder_username] = current_user.username
      params.require(:bid).permit(:stuff_create_time, :owner_username, :bidder_username, :bidding_points, :status, :create_time)
    end
end

project/app/helpers/bids_helper.rb
module BidsHelper
end

project/app/views/bids/_form.html.erb
<%= form_for(bid) do |f| %>
  <% if bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bidding_points %>
    <%= f.text_field :bidding_points %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

project/app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bids</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Stuff create time</th>
      <th>Owner</th>
      <th>Bidder</th>
      <th>Bidding points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.stuff_create_time %></td>
        <td><%= bid.owner_username %></td>
        <td><%= bid.bidder_username %></td>
        <td><%= bid.bidding_points %></td>
        <td><%= link_to 'Show', bid %></td>
        <% if current_user.isAdmin || bid.owner_username == current_user.username %>
          <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
          <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

project/app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Back', bids_path %>

project/app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @bid.owner_username %>
</p>

<p>
  <strong>Bidder:</strong>
  <%= @bid.bidder_username %>
</p>

<p>
  <strong>Bidding points:</strong>
  <%= @bid.bidding_points %>
</p>

<p>
  <strong>Bid create time:</strong>
  <%= @bid.create_time %>
</p>

<% if @bid.owner_username == current_user.username %>
<%= link_to 'Approve', approve_bid_path(@bid), method: :post %> |
<% end %>

<% if @bid.bidder_username == current_user.username %>
<%= link_to 'Destroy', @bid, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_bid_path(@bid) %> |
<% end %>
<%= link_to 'Back', bids_path %>