project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bids do
  	member do
  		post :approve
  	end
  end
  resources :stuffs do
  	member do
  		post :bid, to: 'stuffs#bid_stuff'
  	end
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'stuffs#index'

  resources :reports, only: [] do
    collection do
      get 'popular_pickup'
      get 'popular_return'
    end
  end
end

project/app/models/stuff.rb
class Stuff < ApplicationRecord
	self.primary_keys = :create_time, :owner_username
  belongs_to :user
  has_many :bid

  def self.get_stuff(create_time, owner_username)
    sql = "SELECT * FROM stuffs WHERE create_time='#{create_time} '"\
      "AND owner_username='#{owner_username}'"
    Stuff.find_by_sql(sql).first
  end

  def self.new_stuff(params)
  	stuff_name = params[:stuff_name]
  	stuff_description = params[:stuff_description]
  	stuff_type = params[:stuff_type]
  	create_time = params[:create_time]
    owner_username = params[:owner_username]
    pick_up_point = params[:pick_up_point]
    return_point = params[:return_point]
    pick_up_time = params[:pick_up_time]
    return_time = params[:return_time]
    create_time = params[:create_time]

    sql = "INSERT INTO offers "\
      "(stuff_name, stuff_description, stuff_type, create_time, owner_username, pick_up_point, return_point, pick_up_time, return_time, create_time) "\
      "VALUES ('#{stuff_name}', '#{stuff_description}', '#{stuff_type}', '#{create_time}', '#{owner_username}', '#{pick_up_point}', '#{return_point}', '#{pick_up_time}', '#{return_point}', '#{create_time}');"
    ActiveRecord::Base.connection.execute sql

    [stuff_name, stuff_description, stuff_type, create_time, owner_username, pick_up_point, return_point, pick_up_time, return_time, create_time]
  end

  def self.search_stuff(stuff_name, stuff_type, pick_up_point, return_point, availability)
    sql = "SELECT * FROM stuffs WHERE stuff_name LIKE '%#{stuff_name}%'"
    sql = sql + "AND stuff_type = '#{stuff_type}'" if stuff_type.present?
    sql = sql + "AND pick_up_point LIKE '%#{pick_up_point}%'"
    sql = sql + "AND return_point LIKE '%#{return_point}%'"
    sql = sql + "AND availability IS NULL" if availability == "on"
    Stuff.find_by_sql(sql)
  end

  def self.popular_pickup_points
    sql = 'SELECT s.pick_up_point, COUNT(DISTINCT s.create_time, s.owner_username) AS num_stuffs, ' \
      'COUNT(DISTINCT b.stuff_create_time, b.owner_username, b.bidder_username) AS num_bids '\
      'FROM stuffs s LEFT JOIN bids b ON b.stuff_create_time = s.create_time AND '\
      'b.owner_username = s.owner_username '\
      'GROUP BY s.pick_up_point ORDER BY num_stuffs DESC, num_bids DESC'
    ActiveRecord::Base.connection.execute(sql).each
  end

  def self.popular_return_points
    sql = 'SELECT s.return_point, COUNT(DISTINCT s.create_time, s.owner_username) AS num_stuffs, ' \
      'COUNT(DISTINCT b.stuff_create_time, b.owner_username, b.bidder_username) AS num_bids '\
      'FROM stuffs s LEFT JOIN bids b ON b.stuff_create_time = s.create_time AND '\
      'b.owner_username = s.owner_username '\
      'GROUP BY s.return_point ORDER BY num_stuffs DESC, num_bids DESC'
    ActiveRecord::Base.connection.execute(sql).each
  end
end

project/app/controllers/stuffs_controller.rb
class StuffsController < ApplicationController
  before_action :set_stuff, only: [:show, :edit, :update, :destroy, :bid_stuff]

  # GET /stuffs
  # GET /stuffs.json
  def index
    @stuffs = Stuff.search_stuff(params[:stuff_name], params[:stuff_type], 
      params[:pick_up_point], params[:return_point], params[:availability])
  end

  # GET /stuffs/1
  # GET /stuffs/1.json
  def show
    @bids = Bid.get_stuff_bids(@stuff.create_time, @stuff.owner_username)
  end

  # GET /stuffs/new
  def new
    @stuff = Stuff.new
  end

  # GET /stuffs/1/edit
  def edit
  end

  # POST /stuffs
  # POST /stuffs.json
  def create
    @stuff = Stuff.new(stuff_params)

    respond_to do |format|
      if @stuff.save
        format.html { redirect_to stuffs_url, notice: 'Stuff was successfully created.' }
        format.json { render :show, status: :created, location: @stuff }
      else
        format.html { render :new }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stuffs/1
  # PATCH/PUT /stuffs/1.json
  def update
    respond_to do |format|
      if @stuff.update(stuff_params)
        format.html { redirect_to @stuff, notice: 'Stuff was successfully updated.' }
        format.json { render :show, status: :ok, location: @stuff }
      else
        format.html { render :edit }
        format.json { render json: @stuff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stuffs/1
  # DELETE /stuffs/1.json
  def destroy
    @stuff.destroy
    respond_to do |format|
      format.html { redirect_to stuffs_url, notice: 'Stuff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bid_stuff
    @bid = Bid.new
    @bid.stuff_create_time = @stuff.create_time
    @bid.owner_username = @stuff.owner_username
    @bid.bidder_username = current_user.username
    @bid.bidding_points = params[:bidding_points]
    @bid.create_time = Time.now
    @bid.save
    respond_to do |format|
      format.html { redirect_to stuffs_url, notice: 'Bid was successfully added.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stuff
      @paramss = params[:id].split(',')
      @stuff = Stuff.get_stuff(@paramss[0], @paramss[1])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stuff_params
      params[:stuff][:owner_username] = current_user.username
      params.require(:stuff).permit(:owner_username, :stuff_name, :stuff_description, :stuff_type, :pick_up_point, :return_point, :pick_up_time, :return_time, :cost)
    end
end

project/app/helpers/stuffs_helper.rb
module StuffsHelper
end

project/app/views/stuffs/_bid.html.erb
<% bid_show = "Bidded by #{bid.bidder_username} at #{bid.create_time}" %>
<li><%= link_to bid_show, bid_path(bid) %></li>

project/app/views/stuffs/_form.html.erb
<%= form_for(stuff) do |f| %>
  <% if stuff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stuff.errors.count, "error") %> prohibited this stuff from being saved:</h2>

      <ul>
      <% stuff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stuff_name %>
    <%= f.text_field :stuff_name %>
  </div>

  <div class="field">
    <%= f.label :stuff_description %>
    <%= f.text_area :stuff_description %>
  </div>

  <%= f.label :stuff_type %>
  <%= f.select :stuff_type, options_for_select([['tool', 'tool'], ['appliance', 'appliance'], ['furniture', 'furniture'], ['book', 'book']]) %></p>

  <div class="field">
    <%= f.label :pick_up_point %>
    <%= f.text_field :pick_up_point %>
  </div>

  <div class="field">
    <%= f.label :return_point %>
    <%= f.text_field :return_point %>
  </div>

  <div class="field">
    <%= f.label :pick_up_time %>
    <%= f.datetime_select :pick_up_time %>
  </div>

  <div class="field">
    <%= f.label :return_time %>
    <%= f.datetime_select :return_time %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.text_field :cost %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/app/views/stuffs/bid_stuff.js.erb
// $('td#<%= @bid.stuff.hash %>').prepend('<%= j(render partial: "stuffs/bid", locals: { bid: @bid } ) %>');
location.reload();

project/app/views/stuffs/edit.html.erb
<h1>Editing Stuff</h1>

<%= render 'form', stuff: @stuff %>

<%= link_to 'Show', @stuff %> |
<%= link_to 'Back', stuffs_path %>

project/app/views/stuffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stuffs</h1>

<div class="search-block">
  <%= form_tag stuffs_path, :method => 'get' do %>
    <p>
      <%= label_tag(:stuff_name, "Name:") %>
      <%= text_field_tag :stuff_name, params[:stuff_name] %>
    </p>
    <p>
      <%= label_tag(:stuff_type, "Type:") %>
      <%= select_tag :stuff_type, options_for_select([['tool', 'tool'], ['appliance', 'appliance'], ['furniture', 'furniture'], ['book', 'book']]) %>
    </p>
    <p>
      <%= label_tag(:pick_up_point, "Pick up location:") %>
      <%= text_field_tag :pick_up_point, params[:pick_up_point] %>
    </p>
    <p>
      <%= label_tag(:return_point, "Return location:") %>
      <%= text_field_tag :return_point, params[:return_point] %>
    </p>
    <p>
      <%= label_tag(:availability, "Is available:") %>
      <%= check_box_tag :availability, params[:availability] %>
    </p>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Pickup location</th>
      <th>Return location</th>
      <th>Is Available</th>
      <th>Pick up time</th>
      <th>Return time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stuffs.each do |stuff| %>
      <tr>
        <td><%= stuff.stuff_name %></td>
        <td><%= stuff.stuff_type %></td>
        <td><%= stuff.pick_up_point %></td>
        <td><%= stuff.return_point %></td>
        <td><%= !stuff.availability.present? %></td>
        <td><%= stuff.pick_up_time %></td>
        <td><%= stuff.return_time %></td>

        <% bids = Bid.get_stuff_bids(stuff.create_time, stuff.owner_username) %>
        <% bid_taken = Bid.get_taken_stuff_bid(stuff.create_time, stuff.owner_username) %>
        <% if bid_taken.present? %>
            <td>Taken by <%= bid_taken.bidder_username %></td>
        <% else %>
            <td id="<%= stuff.hash %>">
                <% bids.each do |bid| %>
                    <%= render partial: 'stuffs/bid', locals: { bid: bid } %>
                <% end %> 
                <% my_bid = Bid.get_bid(stuff.create_time, stuff.owner_username, current_user.username) %>
                <% if !stuff.availability.present? && !my_bid.present? %>
              <li>
                    <%= form_tag bid_stuff_path(stuff) do |f| %>
                        <%= text_field_tag :bidding_points %>
                    <%= submit_tag "Bid!" %>
              </li>
              <% end %>
            </td>
        <% end %>
      <% end %>

        <td><%= link_to 'Show', stuff %></td>
        <% if current_user.isAdmin || stuff.owner_username == current_user.username %>
        <td><%= link_to 'Edit', edit_stuff_path(stuff) %></td>
        <td><%= link_to 'Destroy', stuff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stuff', new_stuff_path %>

project/app/views/stuffs/new.html.erb
<h1>New Stuff</h1>

<%= render 'form', stuff: @stuff %>

<%= link_to 'Back', stuffs_path %>

project/app/views/stuffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stuff Name:</strong>
  <%= @stuff.stuff_name %>
</p>

<p>
  <strong>Stuff Type:</strong>
  <%= @stuff.stuff_type %>
</p>

<p>
  <strong>Stuff Details:</strong>
  <%= @stuff.stuff_description %>
</p>

<p>
  <strong>Pickup location:</strong>
  <%= @stuff.pick_up_point %>
</p>

<p>
  <strong>Return location:</strong>
  <%= @stuff.return_point %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @stuff.availability %>
</p>

<p>
  <strong>Pickup time:</strong>
  <%= @stuff.pick_up_time %>
</p>

<p>
  <strong>Return time:</strong>
  <%= @stuff.return_time %>
</p>

<h3>bids</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Stuff</th>
      <th>User</th>
      <th>Point</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
    <tr>
      <td><%= bid.stuff_create_time %></td>
      <td><%= bid.owner_username %></td>
      <td><%= bid.bidder_username %></td>
      <td><%= bid.bidding_points %></td>
      <td><%= link_to 'Show', bid %></td>
      <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
      <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.isAdmin || @stuff.owner_username == current_user.username %>
<%= link_to 'Destroy', @stuff, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_stuff_path(@stuff) %> |
<% end %>

<%= link_to 'Back', stuffs_path %>